import matplotlib.pyplot as plt
import pandas as pd
input1 = input('please enter the path of average reward:')
input2 = input('please enter the path of estimate Q:')
input3 = input('please enter the path of true Q:')
input4 = input('please enter the path of estimate Q in FQE:')
input5 = input('please enter the path of true Q in FQE:')
env = pd.read_csv(input1)
fig,ax = plt.subplots(2,2)
ax[0,0].plot(env.iloc[:, 0], env.iloc[:, 2])
ax[0,0].set_title('average reward')
e_q = pd.read_csv(input2)
ax[0,1].plot(e_q.iloc[:, 0], e_q.iloc[:, 2])
ax[0,1].set_title('estimate_q')
tq = pd.read_csv(input3)
ax[1,0].plot(tq.iloc[:, 0], tq.iloc[:, 2])
ax[1,0].set_title('true_q')
fqee = pd.read_csv(input4)
fqet = pd.read_csv(input5)
ax[1,1].plot(fqee.iloc[:, 0], fqee.iloc[:, 2])
ax[1,1].plot(fqet.iloc[:, 0], fqet.iloc[:, 2])
ax[1,1].set_title('fqe')
plt.show()
